name: aws_policy_expander_minimizer
description: >
  A library for expanding and minimizing AWS policies.
version: 0.0.5
environment: 
  sdk: '>=2.10.0 <3.0.0'
homepage: https://github.com/monkeysecurity/aws_policy_expander_minimizer
dev_dependencies:
  test: ^1.21.6