name: aws_policy_expander_minimizer
description: >
  A library for expanding and minimizing AWS policies.
version: 0.0.5
author: Patrick Kelley <pkelley@netflix.com>
homepage: https://github.com/monkeysecurity/aws_policy_expander_minimizer
dev_dependencies:
  unittest: 0.11.5+4
